# Site settings
title: The Kumuluz Blog
email: info@sunesis.si
description: >
  The Kumuluz range of products offers a wide variety of technological innovations,
  spanning from integration platforms all the way to developer frameworks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.kumuluz.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
